### ISSUE TITLE
data_t uses std::allocator

### ISSUE THREAD

**Issue by Alexhuszagh** [fhajji/sodium-wrapper#1]
One of the major benefits of libsodium is the presence of `sodium_malloc`, allowing controlled access to memory (enabling noaccess, read-write, or read-only access when desired), and `sodium_memzero`, allowing zeroing out memory even with compiler optimizations.

The default data type, `data_t`, uses `std::vector<unsigned char>`, which will then use `std::allocator` as the default allocator. This isn't good, since it does not support `sodium_malloc`, and will not zero out memory by default on destruction. This would expose information like passwords to side channel attacks without mitigating the risk.

What would be an ideal approach would be write a single class: an allocator wrapper around `sodium_malloc` and `sodium_free` (this is ~200 lines of boilerplate) and one around `std::vector` (this is more involved). As long as you use `std::vector`, and not `std::string` (which uses small-string optimization, meaning the destructor is not called for small arrays) or a small-vector optimized vector, this should be secure and fairly trivial to implement.

If you would like, I can gladly provide code freely for that in a pull request.

**Comment by fhajji** [comment]
You're absolutely right. Currently, only sensitive data like key_t in Key and KeyVar use SodiumAlloc (see include/alloc.h). data_t itself doesn't... by design.

The reason why I'm not using SodiumAlloc everywhere is that sodium_malloc()ed memory is a scarce resource.

However, this needs review from a crypto perspective. After all, we don't want to introduce vulnerability to side channel attacks in a wrapper to a library that was carefully designed to prevent just this.

That's why sodium-wrapper is still experimental.

**Comment by fhajji** [comment]
I've thought about this some more.

The only definitively sensitive data in a typical application is key material and in the case of key derivation, the passphrase, seed, or whatever, that led to it. As to plaintext, it depends on the application.

Key material via the key wrapper classes is already in key_t secured memory, so that has hopefully been taken care of already.

Passphrases that are used in key derivation functions should in principle also be in secured memory. Unfortunately, they must originally come from somewhere in insecure memory, like e.g. interactively. While it may be possible to provide a raw pointer to key_t memory to, say, an interactive dialog to store user-entered passphrases, *some* data from the passphrase will already have leaked out anyway while it was being collected and before it was stored. Using secured memory for passphrases would (merely) reduce the time window where it can be grabbed, but still, it may be useful and would make sense.

So what about plaintext and ciphertext?

Ciphertext is not sensitive. It already provides confidentiality (and integrity, if we use the right libsodium box functions and not raw stream ciphers directly). It is intended to be sent as-is over the public Internet anyway, so protecting it in special memory makes little sense to me.

Plaintext can be sensitive though, depending on the application. Think smart cards that decrypt some ciphertext with a key in particularly protected memory, only to decide based on the plaintext to output 1 or 0. So the plaintext isn't disclosed in that case. It better be in secured memory. In other use-cases, plaintext can be huge, like, say, your 1 TB backups. Even chunked, it would be costly to store it in secured memory for processing... especially if all we want is restore the decrypted backup,

To cut a long story short, I think we should redesign / update the API to allow the user to choose between unprotected and protected memory for non-key material.

**Comment by fhajji** [comment]
Alright, I'm currently templating every function and class (where it makes sense) on the bytes type (BT), a container of byte, char, ...

BT can e.g. be sodium::chars, sodium::bytes, sodium::bytes_protected or anything else that can be meaningfully reinterpret_cast<[const] unsigned char *>().

This will allow users to select whatever storage type they desire for in/out params.

BTW, I wished we already had concepts in C++11 to check for required BT traits like, say, data(), size(), ... but well...
